[2022-09-05T23:08:39.284-0400] {plugins_manager.py:292} DEBUG - Plugins are already loaded. Skipping.
[2022-09-05T23:08:39.292-0400] {__init__.py:50} DEBUG - Loading core task runner: StandardTaskRunner
[2022-09-05T23:08:39.303-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-05T23:08:39.308-0400] {base_task_runner.py:70} DEBUG - Planning to run as the  user
[2022-09-05T23:08:39.312-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [queued]> from DB
[2022-09-05T23:08:39.321-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-05T23:08:39.322-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-05T23:08:39.328-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2022-09-05T23:08:39.328-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2022-09-05T23:08:39.329-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [queued]>
[2022-09-05T23:08:39.329-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2022-09-05T23:08:39.329-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-05T23:08:39.329-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-05T23:08:39.335-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2022-09-05T23:08:39.337-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [queued]>
[2022-09-05T23:08:39.337-0400] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T23:08:39.337-0400] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-05T23:08:39.337-0400] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T23:08:39.349-0400] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): curate_yahoo_finance_html> on 2022-09-06 03:08:24.982610+00:00
[2022-09-05T23:08:39.352-0400] {standard_task_runner.py:52} INFO - Started process 78005 to run task
[2022-09-05T23:08:39.364-0400] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_etl', 'curate_yahoo_finance_html', 'manual__2022-09-06T03:08:24.982610+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/var/folders/2z/f_7z97sn6_33j1hnl38wlzs40000gn/T/tmp90vd9b1o', '--error-file', '/var/folders/2z/f_7z97sn6_33j1hnl38wlzs40000gn/T/tmpjezgxx86']
[2022-09-05T23:08:39.366-0400] {standard_task_runner.py:80} INFO - Job 40: Subtask curate_yahoo_finance_html
[2022-09-05T23:08:39.371-0400] {cli_action_loggers.py:66} DEBUG - Calling callbacks: [<function default_action_log at 0x7fa51a3273a0>]
[2022-09-05T23:08:39.387-0400] {settings.py:398} DEBUG - Disposing DB connection pool (PID 78005)
[2022-09-05T23:08:39.388-0400] {settings.py:260} DEBUG - Setting up DB connection pool (PID 78005)
[2022-09-05T23:08:39.388-0400] {settings.py:330} DEBUG - settings.prepare_engine_args(): Using NullPool
[2022-09-05T23:08:39.425-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-05T23:08:39.433-0400] {task_command.py:371} INFO - Running <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [running]> on host FAS-EALC-LIU-2
[2022-09-05T23:08:39.434-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [running]> from DB
[2022-09-05T23:08:39.457-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-05T23:08:39.461-0400] {taskinstance.py:943} DEBUG - Clearing XCom data
[2022-09-05T23:08:39.501-0400] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_etl
AIRFLOW_CTX_TASK_ID=curate_yahoo_finance_html
AIRFLOW_CTX_EXECUTION_DATE=2022-09-06T03:08:24.982610+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-06T03:08:24.982610+00:00
[2022-09-05T23:08:39.502-0400] {__init__.py:146} DEBUG - Preparing lineage inlets and outlets
[2022-09-05T23:08:39.503-0400] {__init__.py:190} DEBUG - inlets: [], outlets: []
[2022-09-05T23:08:39.625-0400] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/jl/Documents/Repos/GHC-2022-data-engineering-workshop/airflow/dags/test_dag.py", line 65, in curate_yahoo_finance_html
    market_price.text,
AttributeError: 'NoneType' object has no attribute 'text'
[2022-09-05T23:08:39.628-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [running]> from DB
[2022-09-05T23:08:39.631-0400] {taskinstance.py:2349} DEBUG - Task Duration set to 0.302232
[2022-09-05T23:08:39.632-0400] {taskinstance.py:1418} DEBUG - Clearing next_method and next_kwargs.
[2022-09-05T23:08:39.633-0400] {taskinstance.py:1407} INFO - Marking task as FAILED. dag_id=test_etl, task_id=curate_yahoo_finance_html, execution_date=20220906T030824, start_date=20220906T030839, end_date=20220906T030839
[2022-09-05T23:08:39.642-0400] {cli_action_loggers.py:84} DEBUG - Calling callbacks: []
[2022-09-05T23:08:39.643-0400] {standard_task_runner.py:92} ERROR - Failed to execute job 40 for task curate_yahoo_finance_html ('NoneType' object has no attribute 'text'; 78005)
[2022-09-05T23:08:39.670-0400] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-05T23:08:39.672-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T03:08:24.982610+00:00 [running]> from DB
[2022-09-05T23:08:39.695-0400] {dagrun.py:642} DEBUG - number of tis tasks for <DagRun test_etl @ 2022-09-06 03:08:24.982610+00:00: manual__2022-09-06T03:08:24.982610+00:00, state:running, queued_at: 2022-09-06 03:08:25.006559+00:00. externally triggered: True>: 3 task(s)
[2022-09-05T23:08:39.695-0400] {dagrun.py:666} DEBUG - number of scheduleable tasks for <DagRun test_etl @ 2022-09-06 03:08:24.982610+00:00: manual__2022-09-06T03:08:24.982610+00:00, state:running, queued_at: 2022-09-06 03:08:25.006559+00:00. externally triggered: True>: 1 task(s)
[2022-09-05T23:08:39.696-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-06T03:08:24.982610+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-05T23:08:39.696-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-06T03:08:24.982610+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-05T23:08:39.696-0400] {taskinstance.py:970} DEBUG - Setting task state for <TaskInstance: test_etl.generate_report manual__2022-09-06T03:08:24.982610+00:00 [None]> to upstream_failed
[2022-09-05T23:08:39.696-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-06T03:08:24.982610+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 2, 'successes': 1, 'skipped': 0, 'failed': 1, 'upstream_failed': 0, 'done': 2}, upstream_task_ids={'hit_wikipedia_api', 'curate_yahoo_finance_html'}
[2022-09-05T23:08:39.696-0400] {taskinstance.py:1161} DEBUG - Dependencies not met for <TaskInstance: test_etl.generate_report manual__2022-09-06T03:08:24.982610+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 2, 'successes': 1, 'skipped': 0, 'failed': 1, 'upstream_failed': 0, 'done': 2}, upstream_task_ids={'hit_wikipedia_api', 'curate_yahoo_finance_html'}
[2022-09-05T23:08:39.706-0400] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
