[2022-09-06T01:04:12.943-0400] {plugins_manager.py:292} DEBUG - Plugins are already loaded. Skipping.
[2022-09-06T01:04:12.952-0400] {__init__.py:50} DEBUG - Loading core task runner: StandardTaskRunner
[2022-09-06T01:04:12.976-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-06T01:04:12.981-0400] {base_task_runner.py:70} DEBUG - Planning to run as the  user
[2022-09-06T01:04:12.988-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [queued]> from DB
[2022-09-06T01:04:12.997-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2022-09-06T01:04:13.006-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2022-09-06T01:04:13.006-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-06T01:04:13.006-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-06T01:04:13.006-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [queued]>
[2022-09-06T01:04:13.011-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2022-09-06T01:04:13.011-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-06T01:04:13.020-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2022-09-06T01:04:13.020-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-06T01:04:13.021-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [queued]>
[2022-09-06T01:04:13.021-0400] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T01:04:13.021-0400] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-06T01:04:13.021-0400] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T01:04:13.038-0400] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): curate_yahoo_finance_html> on 2022-09-06 05:02:39.147953+00:00
[2022-09-06T01:04:13.040-0400] {standard_task_runner.py:52} INFO - Started process 85466 to run task
[2022-09-06T01:04:13.048-0400] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_etl', 'curate_yahoo_finance_html', 'manual__2022-09-06T05:02:39.147953+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/var/folders/2z/f_7z97sn6_33j1hnl38wlzs40000gn/T/tmp2dxd8wcv', '--error-file', '/var/folders/2z/f_7z97sn6_33j1hnl38wlzs40000gn/T/tmp3s0mx0vu']
[2022-09-06T01:04:13.052-0400] {standard_task_runner.py:80} INFO - Job 55: Subtask curate_yahoo_finance_html
[2022-09-06T01:04:13.058-0400] {cli_action_loggers.py:66} DEBUG - Calling callbacks: [<function default_action_log at 0x7faed5c7f430>]
[2022-09-06T01:04:13.074-0400] {settings.py:398} DEBUG - Disposing DB connection pool (PID 85466)
[2022-09-06T01:04:13.075-0400] {settings.py:260} DEBUG - Setting up DB connection pool (PID 85466)
[2022-09-06T01:04:13.076-0400] {settings.py:330} DEBUG - settings.prepare_engine_args(): Using NullPool
[2022-09-06T01:04:13.119-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-06T01:04:13.127-0400] {task_command.py:371} INFO - Running <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [running]> on host FAS-EALC-LIU-2
[2022-09-06T01:04:13.128-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [running]> from DB
[2022-09-06T01:04:13.162-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-09-06T01:04:13.168-0400] {taskinstance.py:943} DEBUG - Clearing XCom data
[2022-09-06T01:04:13.265-0400] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_etl
AIRFLOW_CTX_TASK_ID=curate_yahoo_finance_html
AIRFLOW_CTX_EXECUTION_DATE=2022-09-06T05:02:39.147953+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-06T05:02:39.147953+00:00
[2022-09-06T01:04:13.266-0400] {__init__.py:146} DEBUG - Preparing lineage inlets and outlets
[2022-09-06T01:04:13.267-0400] {__init__.py:190} DEBUG - inlets: [], outlets: []
[2022-09-06T01:04:13.527-0400] {logging_mixin.py:115} INFO - 
Market price:  118.34 
After hours trading price:  119.15
[2022-09-06T01:04:13.528-0400] {python.py:173} INFO - Done. Returned value was: ('118.34', '119.15')
[2022-09-06T01:04:13.541-0400] {__init__.py:107} DEBUG - Lineage called with inlets: [], outlets: []
[2022-09-06T01:04:13.541-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [running]> from DB
[2022-09-06T01:04:13.550-0400] {taskinstance.py:1418} DEBUG - Clearing next_method and next_kwargs.
[2022-09-06T01:04:13.551-0400] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=test_etl, task_id=curate_yahoo_finance_html, execution_date=20220906T050239, start_date=20220906T050413, end_date=20220906T050413
[2022-09-06T01:04:13.551-0400] {taskinstance.py:2349} DEBUG - Task Duration set to 0.544074
[2022-09-06T01:04:13.561-0400] {cli_action_loggers.py:84} DEBUG - Calling callbacks: []
[2022-09-06T01:04:13.604-0400] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-06T01:04:13.605-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-09-06T05:02:39.147953+00:00 [running]> from DB
[2022-09-06T01:04:13.654-0400] {dagrun.py:642} DEBUG - number of tis tasks for <DagRun test_etl @ 2022-09-06 05:02:39.147953+00:00: manual__2022-09-06T05:02:39.147953+00:00, state:running, queued_at: 2022-09-06 05:02:39.220114+00:00. externally triggered: True>: 4 task(s)
[2022-09-06T01:04:13.655-0400] {dagrun.py:666} DEBUG - number of scheduleable tasks for <DagRun test_etl @ 2022-09-06 05:02:39.147953+00:00: manual__2022-09-06T05:02:39.147953+00:00, state:running, queued_at: 2022-09-06 05:02:39.220114+00:00. externally triggered: True>: 1 task(s)
[2022-09-06T01:04:13.657-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-06T05:02:39.147953+00:00 [None]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 3, 'successes': 2, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 2}, upstream_task_ids={'hit_wikipedia_api', 'curate_yahoo_finance_html', 'curate_bing_news_html'}
[2022-09-06T01:04:13.657-0400] {taskinstance.py:1161} DEBUG - Dependencies not met for <TaskInstance: test_etl.generate_report manual__2022-09-06T05:02:39.147953+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 3, 'successes': 2, 'skipped': 0, 'failed': 0, 'upstream_failed': 0, 'done': 2}, upstream_task_ids={'hit_wikipedia_api', 'curate_yahoo_finance_html', 'curate_bing_news_html'}
[2022-09-06T01:04:13.658-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-06T05:02:39.147953+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-09-06T01:04:13.659-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.generate_report manual__2022-09-06T05:02:39.147953+00:00 [None]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-09-06T01:04:13.672-0400] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
