[2022-08-31T17:29:23.132-0400] {plugins_manager.py:292} DEBUG - Plugins are already loaded. Skipping.
[2022-08-31T17:29:23.140-0400] {__init__.py:50} DEBUG - Loading core task runner: StandardTaskRunner
[2022-08-31T17:29:23.149-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-08-31T17:29:23.154-0400] {base_task_runner.py:70} DEBUG - Planning to run as the  user
[2022-08-31T17:29:23.158-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [queued]> from DB
[2022-08-31T17:29:23.166-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-08-31T17:29:23.166-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2022-08-31T17:29:23.172-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-08-31T17:29:23.172-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2022-08-31T17:29:23.172-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2022-08-31T17:29:23.173-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [queued]>
[2022-08-31T17:29:23.173-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-08-31T17:29:23.179-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2022-08-31T17:29:23.179-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2022-08-31T17:29:23.180-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-08-31T17:29:23.182-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2022-08-31T17:29:23.183-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [queued]>
[2022-08-31T17:29:23.183-0400] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-08-31T17:29:23.183-0400] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-08-31T17:29:23.183-0400] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-08-31T17:29:23.195-0400] {taskinstance.py:1389} INFO - Executing <Task(_PythonDecoratedOperator): scrape_yahoo_finance> on 2022-08-31 21:29:19.880753+00:00
[2022-08-31T17:29:23.198-0400] {standard_task_runner.py:52} INFO - Started process 11252 to run task
[2022-08-31T17:29:23.211-0400] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_etl', 'scrape_yahoo_finance', 'manual__2022-08-31T21:29:19.880753+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/var/folders/2z/f_7z97sn6_33j1hnl38wlzs40000gn/T/tmpq5h6k0ku', '--error-file', '/var/folders/2z/f_7z97sn6_33j1hnl38wlzs40000gn/T/tmptcukf8nr']
[2022-08-31T17:29:23.214-0400] {standard_task_runner.py:80} INFO - Job 22: Subtask scrape_yahoo_finance
[2022-08-31T17:29:23.221-0400] {cli_action_loggers.py:66} DEBUG - Calling callbacks: [<function default_action_log at 0x7f781ab273a0>]
[2022-08-31T17:29:23.241-0400] {settings.py:398} DEBUG - Disposing DB connection pool (PID 11252)
[2022-08-31T17:29:23.242-0400] {settings.py:260} DEBUG - Setting up DB connection pool (PID 11252)
[2022-08-31T17:29:23.243-0400] {settings.py:330} DEBUG - settings.prepare_engine_args(): Using NullPool
[2022-08-31T17:29:23.289-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-08-31T17:29:23.298-0400] {task_command.py:371} INFO - Running <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [running]> on host FAS-EALC-LIU-2
[2022-08-31T17:29:23.299-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [running]> from DB
[2022-08-31T17:29:23.332-0400] {taskinstance.py:1107} DEBUG - previous_execution_date was called
[2022-08-31T17:29:23.337-0400] {taskinstance.py:943} DEBUG - Clearing XCom data
[2022-08-31T17:29:23.384-0400] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_etl
AIRFLOW_CTX_TASK_ID=scrape_yahoo_finance
AIRFLOW_CTX_EXECUTION_DATE=2022-08-31T21:29:19.880753+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-31T21:29:19.880753+00:00
[2022-08-31T17:29:23.385-0400] {__init__.py:146} DEBUG - Preparing lineage inlets and outlets
[2022-08-31T17:29:23.385-0400] {__init__.py:190} DEBUG - inlets: [], outlets: []
[2022-08-31T17:29:23.572-0400] {logging_mixin.py:115} INFO - About to send request to Yahoo Finance
[2022-08-31T17:29:23.823-0400] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGSEGV
[2022-08-31T17:29:23.825-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [running]> from DB
[2022-08-31T17:29:23.840-0400] {taskinstance.py:871} DEBUG - Refreshing TaskInstance <TaskInstance: test_etl.scrape_yahoo_finance manual__2022-08-31T21:29:19.880753+00:00 [running]> from DB
[2022-08-31T17:29:23.846-0400] {taskinstance.py:2349} DEBUG - Task Duration set to 0.673126
[2022-08-31T17:29:23.847-0400] {taskinstance.py:1418} DEBUG - Clearing next_method and next_kwargs.
[2022-08-31T17:29:23.847-0400] {taskinstance.py:1407} INFO - Marking task as FAILED. dag_id=test_etl, task_id=scrape_yahoo_finance, execution_date=20220831T212919, start_date=20220831T212923, end_date=20220831T212923
[2022-08-31T17:29:23.872-0400] {dagrun.py:642} DEBUG - number of tis tasks for <DagRun test_etl @ 2022-08-31 21:29:19.880753+00:00: manual__2022-08-31T21:29:19.880753+00:00, state:running, queued_at: 2022-08-31 21:29:19.895047+00:00. externally triggered: True>: 2 task(s)
[2022-08-31T17:29:23.873-0400] {dagrun.py:666} DEBUG - number of scheduleable tasks for <DagRun test_etl @ 2022-08-31 21:29:19.880753+00:00: manual__2022-08-31T21:29:19.880753+00:00, state:running, queued_at: 2022-08-31 21:29:19.895047+00:00. externally triggered: True>: 1 task(s)
[2022-08-31T17:29:23.873-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-08-31T21:29:19.880753+00:00 [None]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2022-08-31T17:29:23.873-0400] {taskinstance.py:970} DEBUG - Setting task state for <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-08-31T21:29:19.880753+00:00 [None]> to upstream_failed
[2022-08-31T17:29:23.873-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-08-31T21:29:19.880753+00:00 [upstream_failed]> dependency 'Trigger Rule' PASSED: False, Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 1, 'upstream_failed': 0, 'done': 1}, upstream_task_ids={'scrape_yahoo_finance'}
[2022-08-31T17:29:23.874-0400] {taskinstance.py:1161} DEBUG - Dependencies not met for <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-08-31T21:29:19.880753+00:00 [upstream_failed]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_tasks_state={'total': 1, 'successes': 0, 'skipped': 0, 'failed': 1, 'upstream_failed': 0, 'done': 1}, upstream_task_ids={'scrape_yahoo_finance'}
[2022-08-31T17:29:23.874-0400] {taskinstance.py:1181} DEBUG - <TaskInstance: test_etl.curate_yahoo_finance_html manual__2022-08-31T21:29:19.880753+00:00 [upstream_failed]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2022-08-31T17:29:23.942-0400] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
